version: '3.4'
services:
  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - TZ=Asia/Shanghai
    restart: "unless-stopped"